[phases.setup]
aptPkgs = ["libatomic1"]

[build]
buildCommand = "cd backend && npm install && cd ../frontend-v2 && npm install --include=dev && npm run build"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
