[build]
buildCommand = "cd backend && npm install && cd ../frontend-v2 && npm install --include=dev && VITE_MAP_API_KEY='' npm run build && cd ../landing-v2 && npm install --include=dev && npm run build"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
