[build]
buildCommand = "npm --prefix backend install && npm --prefix frontend-v2 install --include=dev && npm --prefix landing-v2 install --include=dev && VITE_MAP_API_KEY='' npm run build"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
